base_url = "https://www.getmello.org"

title = "Mello"
description = "Easing your mind whenever you need us."

default_language = "en"

compile_sass = true
minify_html = true
outdir_dir = "out"

generate_feed = true
feed_filename = "atom.xml"

build_search_index = false

[markdown]
highlight_code = false
render_emoji = true
external_links_target_blank = true

